### ISSUE TITLE
feat: Additional capture device options

### ISSUE THREAD

**Issue by CillianMyles** [alnitak/flutter_recorder#13]
## Description

My ultimate goal is to be able to not choose/allow microphones which use the HFP protocol over bluetooth because it is really low quality for voice recording. 

I would always prefer the built-in microphone on mobile, while on desktop I guess it makes sense to have more information and granular control about microphone selection.

## Option 1

- [ ] Expose an option which allows me, the plugin consumer, to not choose/allow HFP bluetooth microphones

iOS example:

`record` and indeed the `AVAudioSession` APIs it relies upon provides a number of configurations that would be useful here:
- https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions-swift.struct/defaulttospeaker
- https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions-swift.struct/allowbluetooth
- https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions-swift.struct/allowbluetootha2dp

But of course there are a couple of problems with this:
1. We need to support all platforms, not just iOS
2. I'm not sure what Core Audio provides in this regard and hence why I am also suggesting:

## Option 2

- [ ] Extend `CaptureDevice` with a bit more information so that plugin consumers can make their own judgement based on the microphone type. 

Something alone the lines of:

```dart
/// CaptureDevice exposed to Dart
final class CaptureDevice {
  /// Constructs a new [CaptureDevice].
  const CaptureDevice(this.name, this.isDefault, this.id);

  /// The name of the device.
  final String name;

  /// Whether this is the default capture device.
  final bool isDefault;

  /// The ID of the device.
  final int id;

  /// The type of the device.
  final CaptureDeviceType type;
}

enum CaptureDeviceType {
  builtIn,
  bluetooth,
  usb,
  virtual;
}
```

**Comment by alnitak** [comment]
Unfortunately, the only informations that miniaudio exposes are already in `CaptureDevice`.

I didn't find a way to determine the mic type in miniaudio, maybe this can be done just by looking at the device name?
