### ISSUE TITLE
Error (Xcode): Undefined symbol: _AVAudioSessionCategoryAmbient

### ISSUE THREAD

**Issue by oliverbytes** [alnitak/flutter_recorder#14]
**Description**

Errors when running to an iOS device:

```
Could not build the precompiled application for the device.
Error (Xcode): Undefined symbol: _AVAudioSessionCategoryAmbient

Error (Xcode): Undefined symbol: _AVAudioSessionCategoryMultiRoute

Error (Xcode): Undefined symbol: _AVAudioSessionCategoryPlayAndRecord

Error (Xcode): Undefined symbol: _AVAudioSessionCategoryPlayback

Error (Xcode): Undefined symbol: _AVAudioSessionCategoryRecord

Error (Xcode): Undefined symbol: _AVAudioSessionCategorySoloAmbient

Error (Xcode): Undefined symbol: _AVAudioSessionInterruptionNotification

Error (Xcode): Undefined symbol: _AVAudioSessionInterruptionTypeKey

Error (Xcode): Undefined symbol: _AVAudioSessionRouteChangeNotification

Error (Xcode): Undefined symbol: _AVAudioSessionRouteChangeReasonKey

Error (Xcode): Undefined symbol: _AudioComponentFindNext

Error (Xcode): Undefined symbol: _AudioComponentInstanceDispose

Error (Xcode): Undefined symbol: _AudioComponentInstanceNew

Error (Xcode): Undefined symbol: _AudioOutputUnitStart

Error (Xcode): Undefined symbol: _AudioOutputUnitStop

Error (Xcode): Undefined symbol: _AudioUnitAddPropertyListener

Error (Xcode): Undefined symbol: _AudioUnitGetProperty

Error (Xcode): Undefined symbol: _AudioUnitGetPropertyInfo

Error (Xcode): Undefined symbol: _AudioUnitInitialize

Error (Xcode): Undefined symbol: _AudioUnitRender

Error (Xcode): Undefined symbol: _AudioUnitSetProperty

Error (Xcode): Undefined symbol: _OBJC_CLASS_$_AVAudioSession
```

**Steps To Reproduce**

Just add the package and run on real ios device

**Comment by alnitak** [comment]
Hi @oliverbytes,

could you please try with the `autogain` branch?

In `pubspec.yaml` please try:
```
  flutter_recorder:
    git:
      url: git@github.com:alnitak/flutter_recorder.git
      ref: autogain
```

**Comment by kiaxseventh** [comment]
hello dear @alnitak 
Thank you for your response! I tried using the autogain branch as you suggested by updating my pubspec.yaml 

However, I encountered a different error after making this change. Here is the error message I received:

`
Resolving dependencies...
Git error. Command: `git clone --mirror git@github.com:alnitak/flutter_recorder.git /Users/kiax/.pub-cache/_temp/diryykgYy`
stdout: 
stderr: Cloning into bare repository '/Users/kiax/.pub-cache/_temp/diryykgYy'...
Connection closed by 140.82.121.4 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
`

**Comment by kiaxseventh** [comment]
@alnitak
I updated my pubspec.yaml as follows:

```
  flutter_recorder:
    git:
      url: https://github.com/alnitak/flutter_recorder.git
      ref: autogain
```

I tested the autogain branch, and it successfully resolves the issue with running on iOS. Everything works perfectly now.
Thank you for your support

**Comment by alnitak** [comment]
Oh yes, `https` not `git@` in pubspec, sorry! Thanks @kiaxseventh 

Tomorrow I will merge it and update it on pub.dev
