### ISSUE TITLE
fix: MacOS error when listCaptureDevices was called

### ISSUE THREAD

**Issue by guoz2013** [alnitak/flutter_recorder#15]
**Description**

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unsupported operation: Operation 'toDartString' not allowed on a 'nullptr'.
#0      Utf8Pointer._ensureNotNullptr (package:ffi/src/utf8.dart:61:7)
#1      Utf8Pointer.toDartString (package:ffi/src/utf8.dart:41:5)
#2      RecorderFfi.listCaptureDevices (package:flutter_recorder/src/bindings/recorder_io.dart:152:33)
#3      Recorder.listCaptureDevices (package:flutter_recorder/src/flutter_recorder.dart:190:33)

**Steps To Reproduce**

` Recorder.instance.listCaptureDevices();`

**Comment by alnitak** [comment]
Seems that the OS doesn't give a name to your input device! Anyway, I fixed this in this repo. Please try it!
Feel free to reopen if the problem persists.
