### ISSUE TITLE
fix: RecorderNotInitializedException: The recorder has not been initialized yet (on the C++ side).

### ISSUE THREAD

**Issue by tolink-Mengtianfu** [alnitak/flutter_recorder#16]
**Description**

Follow the example code to initialize the exception

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

`startRecording(){
    Permission.microphone.request().isGranted.then((value) async {
      if (!value) {
        await [Permission.microphone].request();
      }
    });

    /// Initialize the capture device and start it:
    try {
      Recorder.instance.init();
      Recorder.instance.start();
    } on Exception catch (e) {
      debugPrint('init() error: $e\n');
      return;
    }
    if(isRecord.value){
      Recorder.instance.stopRecording();
      isRecord.value = false;
      return;
    }

    isRecord.value = true;

    //Start recording:
    Recorder.instance.startRecording(completeFilePath: "audioCompleteFilenameWithPath.wav");
    /// Listen to audio data stream. The data is received in Uint8List.
    Recorder.instance.uint8ListStream.listen((data) {
      /// the [data] is of type `AudioDataContainer` and, whatever format is passed to
      /// the `init()` method, it is available with [data.rawData] which is of `Uint8List`
      /// type. This is useful if we want to write into a file.
      /// It is possible to convert audio data to the desired format using one of the
      /// `data.to[*]List` methods. Be aware that the conversion is compute expensive and
      /// should be avoided if possible initializing the recorder with the format
      /// desired.
      double db = Recorder.instance.getVolumeDb();
      debugPrint("db:$db");

    });

    /// Start streaming:
    Recorder.instance.startStreamingData();
  }`

**Comment by tolink-Mengtianfu** [comment]
I'm running on iOS18

**Comment by tolink-Mengtianfu** [comment]
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.1 24B83 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.95.3)
[!] Proxy Configuration
    ! NO_PROXY is not set
[✓] Connected device (4 available)
   
[✓] Network resources

**Comment by alnitak** [comment]
Hi @tolink-Mengtianfu,

I think your `startRecording()` shoud be:
```
Future<void> startRecording() async{
  await Permission.microphone.request().isGranted.then((value) async {
  if (!value) {
    await [Permission.microphone].request();
  }
});
```
That method must be awaited as like `Recorder.instance.init();`. If you call some other methods without initializing the recorder, that error arises. If you don't use the `await` on the `init()` it will execute the next lines without entering yet in the `init()`.
