### ISSUE TITLE
feat: Visualizer From File

### ISSUE THREAD

**Issue by jtkeyva** [alnitak/flutter_recorder#4]
**Description**

The visualizer handles input from the mic very well. Really great job!
Can it visualize audio coming from a sound file or video file?

**Requirements**

"Listen" and visualize audio from other sources besides mic. 

**Additional Context**

A working example would be great.

**Comment by alnitak** [comment]
Hey @jtkeyva!

To manage output sound, you could consider [flutter_soloud](https://github.com/alnitak/flutter_soloud) which is intended also for visualizing data. You can find an example [here](https://github.com/alnitak/flutter_soloud/blob/main/example/lib/audio_data/audio_data.dart).

For a more in-depth example please look [here](https://github.com/alnitak/flutter_soloud_example) (I need to update some code in the filters example tab, it still uses some deprecated methods).
[Here is a web example](https://marcobavagnoli.com/flutter_soloud_example/).

**Comment by jtkeyva** [comment]
oh ya wow, that's exactly it. thanks! works great. any reason ios 13 is needed?

**Comment by alnitak** [comment]
> any reason ios 13 is needed?

in `flutter_soloud` I needed a lib that was introduced in ios 13.

I close this issue since it is "resolved". Feel free to reopen!
