### ISSUE TITLE
fix: Failed to run on Android

### ISSUE THREAD

**Issue by HarithHaroon** [alnitak/flutter_recorder#6]
**Description**

Not a bug, but I'm struggling to run it on Android.
The package uses NDK 25.1.8937393
Android Studio automatically installs NDK 28.0.12433566

If there's something that can help me fix this please let me know! 

Thanks in advance 

**Screenshots**

![Screenshot from 2024-11-17 20-54-15](https://github.com/user-attachments/assets/777a42ea-d1be-463e-8a3b-320fb065e451)

**Comment by alnitak** [comment]
I don't know why this happens. You could try to comment out [this](https://github.com/alnitak/flutter_recorder/blob/210f27a025b484e0feceec2ac840d5a76875492b/android/build.gradle#L40) line or put there the NDK version you are using.

Let me know! Thank you.

**Comment by alnitak** [comment]
`libflutter_recorder.so` is the lib to be compiled, but you got that NDK compilation error therefore it cannot find it.

Does this happen after you followed my previous suggestion?

**Comment by HarithHaroon** [comment]
Yes

Does it auto-compile or how to do it if manually?

**Comment by alnitak** [comment]
You should see if there are some compilation errors running: `flutter build linux -t lib/main.dart`
You could add a `-v` for the verbose output.

If some errors occur, the `libflutter_recorder.so` lib is not available.

**Comment by HarithHaroon** [comment]
Some errors occurred after running that command, how to add that lib then?

**Comment by alnitak** [comment]
If it compiles then it will be added automatically. What is the relevant output where some compilation error occurs?

**Comment by HarithHaroon** [comment]
![Screenshot from 2024-11-18 12-52-13](https://github.com/user-attachments/assets/40d596e3-e70c-4b1a-b571-e617e8e75841)

![Screenshot from 2024-11-18 12-52-47](https://github.com/user-attachments/assets/2b0a6193-436e-4d15-a6d6-7a0c1157e946)

**Comment by alnitak** [comment]
Oh yes, you need to install `gstreamer` Linux package. I thought it was a pretty much mandatory package in Linux.

Let me know!

**Comment by HarithHaroon** [comment]
Still the same error!

**Comment by alnitak** [comment]
> Still the same error!
> is there any chance I'm missing something? Just add the package to pubspec.yaml and run?

The `gstreamer` is a Linux package as I wrote before. You should install it with your Linux distro package manager. I found [this doc](https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c) to install it.

**Comment by HarithHaroon** [comment]
I did install gstreamer

**Comment by alnitak** [comment]
> I did install gstreamer

So now it compile and this error message doesn't come up again:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)]
Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libflutter_recorder.so': dlopen failed: library "libflutter_recorder.so" not found
```

So now, I didn't understand if you can run the app or if there is something more. Please tell me if some error messages come up and the log if any, or some more details on what is going wrong.

**Comment by HarithHaroon** [comment]
So I've just created a new project 

added the package to pubspec.yaml

changed minSdk to 21 in app/build.gradle

added the permission to AndroidManifest.xml

The app runs, when I call the recorder to init() it throws the same error

This is the counter app example:



![Screenshot from 2024-11-18 17-33-01](https://github.com/user-attachments/assets/9a8494e4-1b98-4adb-8b55-cba92ac53ad9)


The error with stacktrace:

![Screenshot from 2024-11-18 17-28-37](https://github.com/user-attachments/assets/15aa3546-0877-43d6-8ce5-ea2727c2d256)

**Comment by alnitak** [comment]
It still cannot find the compiled library `libflutter_recorder.so`.

I do not understand if you still see compilation errors doing what is described in the [previous](https://github.com/alnitak/flutter_recorder/issues/6#issuecomment-2482589363) comment.

**Comment by HarithHaroon** [comment]
Some good news, running this command

flutter build linux -t lib/main.dart

in the new project now, build is successful and it runs too, I start the recorder without any issue on Linux

on Android it still says 

Failed to load dynamic library libflutter_recorder.so.

**Comment by alnitak** [comment]
I still need to see the android compilation log, but I think that if you run `flutter clean`, `flutter pub get` you could then build it successfully

**Comment by HarithHaroon** [comment]
I did `flutter clean` and `flutter pub get`

The app compiles, this is the log when I call the `init()` method

`E/flutter ( 8914): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libflutter_recorder.so': dlopen failed: library "libflutter_recorder.so" not found
E/flutter ( 8914): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 8914): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 8914): #2      RecorderFfi._dylib.<anonymous closure> (package:flutter_recorder/src/bindings/recorder_io.dart:41:33)
E/flutter ( 8914): #3      RecorderFfi._dylib (package:flutter_recorder/src/bindings/recorder_io.dart:47:4)
E/flutter ( 8914): #4      RecorderFfi._dylib (package:flutter_recorder/src/bindings/recorder_io.dart)
E/flutter ( 8914): #5      new RecorderFfi (package:flutter_recorder/src/bindings/recorder_io.dart:50:69)
E/flutter ( 8914): #6      new RecorderController._ (package:flutter_recorder/src/bindings/recorder_io.dart:23:12)
E/flutter ( 8914): #7      new RecorderController (package:flutter_recorder/src/bindings/recorder_io.dart:20:68)
E/flutter ( 8914): #8      new Recorder._ (package:flutter_recorder/src/flutter_recorder.dart:66:22)
E/flutter ( 8914): #9      Recorder.instance (package:flutter_recorder/src/flutter_recorder.dart:64:45)
E/flutter ( 8914): #10     Recorder.instance (package:flutter_recorder/src/flutter_recorder.dart)
E/flutter ( 8914): #11     _MyHomePageState._incrementCounter (package:recorder/main.dart:39:31)
E/flutter ( 8914): #12     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170:21)
E/flutter ( 8914): #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
E/flutter ( 8914): #14     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656:11)
E/flutter ( 8914): #15     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313:5)
E/flutter ( 8914): #16     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:283:7)
E/flutter ( 8914): #17     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:169:27)
E/flutter ( 8914): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:505:20)
E/flutter ( 8914): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481:22)
E/flutter ( 8914): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
E/flutter ( 8914): #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426:7)
E/flutter ( 8914): #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389:5)
E/flutter ( 8914): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336:7)
E/flutter ( 8914): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305:9)
E/flutter ( 8914): #25     _invoke1 (dart:ui/hooks.dart:328:13)
E/flutter ( 8914): #26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
E/flutter ( 8914): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)E/flutter ( 8914): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libflutter_recorder.so': dlopen failed: library "libflutter_recorder.so" not found
E/flutter ( 8914): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 8914): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 8914): #2      RecorderFfi._dylib.<anonymous closure> (package:flutter_recorder/src/bindings/recorder_io.dart:41:33)
E/flutter ( 8914): #3      RecorderFfi._dylib (package:flutter_recorder/src/bindings/recorder_io.dart:47:4)
E/flutter ( 8914): #4      RecorderFfi._dylib (package:flutter_recorder/src/bindings/recorder_io.dart)
E/flutter ( 8914): #5      new RecorderFfi (package:flutter_recorder/src/bindings/recorder_io.dart:50:69)
E/flutter ( 8914): #6      new RecorderController._ (package:flutter_recorder/src/bindings/recorder_io.dart:23:12)
E/flutter ( 8914): #7      new RecorderController (package:flutter_recorder/src/bindings/recorder_io.dart:20:68)
E/flutter ( 8914): #8      new Recorder._ (package:flutter_recorder/src/flutter_recorder.dart:66:22)
E/flutter ( 8914): #9      Recorder.instance (package:flutter_recorder/src/flutter_recorder.dart:64:45)
E/flutter ( 8914): #10     Recorder.instance (package:flutter_recorder/src/flutter_recorder.dart)
E/flutter ( 8914): #11     _MyHomePageState._incrementCounter (package:recorder/main.dart:39:31)
E/flutter ( 8914): #12     _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1170:21)
E/flutter ( 8914): #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
E/flutter ( 8914): #14     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656:11)
E/flutter ( 8914): #15     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:313:5)
E/flutter ( 8914): #16     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:283:7)
E/flutter ( 8914): #17     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:169:27)
E/flutter ( 8914): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:505:20)
E/flutter ( 8914): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481:22)
E/flutter ( 8914): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450:11)
E/flutter ( 8914): #21     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426:7)
E/flutter ( 8914): #22     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389:5)
E/flutter ( 8914): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336:7)
E/flutter ( 8914): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305:9)
E/flutter ( 8914): #25     _invoke1 (dart:ui/hooks.dart:328:13)
E/flutter ( 8914): #26     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
E/flutter ( 8914): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)`

**Comment by alnitak** [comment]
It runs, but for sure it compiles with errors because after running, it cannot find `libflutter_recorder.so`.

So you should see the compile output and paste here the relevant log where you see the error.

Try with `flutter build appbundle -t lib/main.dart`

**Comment by HarithHaroon** [comment]
The mentioned log above is the only thing that I get, also the appbundle has no issues.

![Screenshot from 2024-11-18 19-05-34](https://github.com/user-attachments/assets/d9da7e14-607f-48e9-b4ba-5d944a56d941)

**Comment by alnitak** [comment]
I'm out of ideas! On my end I have no problems with Android.

Have you also tried to run the provided example?

**Comment by HarithHaroon** [comment]
Hello!

I've tried to run the example from the flutter_recorder repo, using Android Studio gradle sync was successful

It downloaded ndk 23

After that I've tried to run the app and got this:


`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_recorder:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/harith/Downloads/temp/flutter_recorder/android/.cxx/Debug/5q173l70/arm64-v8a'
  [1/3] Building CXX object CMakeFiles/flutter_recorder.dir/capture.cpp.o
  FAILED: CMakeFiles/flutter_recorder.dir/capture.cpp.o 
  /home/harith/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/harith/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/harith/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDART_SHARED_LIB -Dflutter_recorder_EXPORTS -I/home/harith/Downloads/temp/flutter_recorder/src -I/home/harith/Downloads/temp/flutter_recorder/src/fft -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/flutter_recorder.dir/capture.cpp.o -MF CMakeFiles/flutter_recorder.dir/capture.cpp.o.d -o CMakeFiles/flutter_recorder.dir/capture.cpp.o -c /home/harith/Downloads/temp/flutter_recorder/src/capture.cpp
  In file included from /home/harith/Downloads/temp/flutter_recorder/src/capture.cpp:6:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  [2/3] Building CXX object CMakeFiles/flutter_recorder.dir/flutter_recorder.cpp.o
  FAILED: CMakeFiles/flutter_recorder.dir/flutter_recorder.cpp.o 
  /home/harith/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/home/harith/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/harith/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDART_SHARED_LIB -Dflutter_recorder_EXPORTS -I/home/harith/Downloads/temp/flutter_recorder/src -I/home/harith/Downloads/temp/flutter_recorder/src/fft -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/flutter_recorder.dir/flutter_recorder.cpp.o -MF CMakeFiles/flutter_recorder.dir/flutter_recorder.cpp.o.d -o CMakeFiles/flutter_recorder.dir/flutter_recorder.cpp.o -c /home/harith/Downloads/temp/flutter_recorder/src/flutter_recorder.cpp
  In file included from /home/harith/Downloads/temp/flutter_recorder/src/flutter_recorder.cpp:3:
  In file included from /home/harith/Downloads/temp/flutter_recorder/src/miniaudio.h:12036:
  /home/harith/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/sys/system_properties.h:76:3: error: expected function body after function declarator
    __INTRODUCED_IN(19);
    ^
  In file included from /home/harith/Downloads/temp/flutter_recorder/src/flutter_recorder.cpp:9:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  2 errors generated.
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      /home/harith/Android/Sdk/cmake/3.18.1/bin/ninja \
        -C \
        /home/harith/Downloads/temp/flutter_recorder/android/.cxx/Debug/5q173l70/arm64-v8a \
        flutter_recorder
    from /home/harith/Downloads/temp/flutter_recorder/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Error: Gradle task assembleDebug failed with exit code 1
`

**Comment by alnitak** [comment]
If I remember well, I read that Flutter installed using `snap` can cause problems like this with native plugins. Have you installed it with snap?

The only solution I found is to uninstall it with `sudo snap remove flutter` and install it the [official way](https://flutter-ko.dev/get-started/install/linux).

Please, let me know.

**Comment by HarithHaroon** [comment]
Wow! that's new

I hear lots of people not liking snaps, they give me troubles sometimes too.

OK, I will try that and let you know.

**Comment by HarithHaroon** [comment]
I've reinstalled flutter, and removed it from `snap`

The example app runs and the recording works.

At some point I changed gradle file including ` ndkVersion = "23.1.7779620"`  that downloaded the version which the plugin uses

Now I create new app samples and add the permissions and normal steps, the  `init()` and `start()` methods both work

`stop()` and `deinit()` work as well, `startRecording()` throws an exception that says:

`RecorderFailedToInitializeRecordingException: The recording failed to start (on the C++ side)`

I'm calling these methods in a row:

`final recorder = Recorder.instance;
  void init() async {
    if (defaultTargetPlatform == TargetPlatform.android ||
        defaultTargetPlatform == TargetPlatform.iOS ||
        defaultTargetPlatform == TargetPlatform.macOS) {
      await Permission.microphone.request().isGranted.then((value) async {
        if (!value) {
          await [Permission.microphone].request();
        }
      });

      recorder.init();
    }`

then `start` then `startRecording` each on a separate button.

**Comment by alnitak** [comment]
On all platforms except the web, you must provide the `completeFilePath` to the `startRecording`.  On web, the browser will ask for the filename.
I forgot to assert this!

On Android, you have to get a folder using [path_provider](https://pub.dev/packages/path_provider) plugin and append the file name you wish to use as you can see in the [example](https://github.com/alnitak/flutter_recorder/blob/210f27a025b484e0feceec2ac840d5a76875492b/example/lib/main.dart#L142).

Thanks for your findings on this issue, I think we can close it. Feel free to reopen (or open another one).
